--INSERT DE CATEGORIAS
insert into categoria (nm_categoria) values ('HORTALI�AS E LEGUMES');
insert into categoria (nm_categoria) values ('FRUTAS');
insert into categoria (nm_categoria) values ('ERVAS E TEMPEROS');
insert into categoria (nm_categoria) values ('DIVERSOS');



--INSERT DE PRODUTOS
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Alface America P�',3.90);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Alface Crespa P�',3.90);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Alho Por� 300g',6.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Ab�bora 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Ab�bora KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Abobrinha It�lia 500',7.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Abobrinha It�lia KG',13.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Batata Inglesa 500g',8.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Batata Inglesa KG',16.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Batata Doce 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Batata Doce KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Beringela 500g',6.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Beringela KG',12.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Beterraba 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Beterraba KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Cebola 500g',8.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Cebola KG',15.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Cebola Roxa 500g',8.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Cebola Roxa KG',15.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Cenoura 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Cenoura KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Couve maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Chuchu 500g',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Chuchu KG',8.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Mandioca s/casca 500',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Mandioca s/casca KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Quiabo 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Quiabo KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Repolho 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Repolho KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Tomate salada 500g',7.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Tomate salada KG',14.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Tomate Italiano 500g',7.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (1,'Tomate Italiano KG',14.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Abacate 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Abacate KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Limão Taiti 500g',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Limão Taiti KG',8.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Limão Cravo 500g',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Limão Cravo KG',8.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Laranja Pêra 500g',6.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Laranja Pêra KG',12.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Mamão KG',12.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Mexerica 500g',5.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Mexerica KG',9.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Banana Prata 500g',5.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Banana Prata KG',9.80);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Banana da Terra KG',18.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Maracujá 500g',7.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (2,'Maracujá KG',14.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Capim Santo 100g',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Coentro e Ceb Maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Cebolinha Maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Salsinha Maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Salsinha e ceb maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Manjericão maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Hortelã maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (3,'Citronela maço',4.50);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (4,'Geléia Morango 200g',22.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (4,'Molho de Tomate 250g',22.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (4,'Ovos Caipiras 12un',17.00);
insert into produto(id_categoria_fk, nm_produto, vl_produto) values (4,'Shimeji Desidratado Pacote',16.00);